# #配置文件
# language: node.js
# node_js:
#     - '10'
# #travis-ci caching
# cache:
#   directories:
#     - node_modules
# # s: build lifecycle
# install:
#   - npm install
# # 脚本
# script:
#   - npm run test:unit
# after_success:
#   - npm run coverage

  {
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "10"
  ],
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "install": [
    "npm install"
  ],
  "script": [
    "npm run test:unit"
  ],
  "after_success": [
    "npm run coverage"
  ]
}